"""
CI Formatter Service

Generates formatted markdown comments for GitHub PR integration.
"""

from typing import List, Dict, Any, Optional


def format_pr_comment(
    pr_identifier: str,
    mode: str,
    critical_count: int,
    warning_count: int,
    info_count: int,
    deviations: List[Dict[str, Any]],
    should_fail: bool,
    commit_sha: Optional[str] = None,
    duration_seconds: float = 0,
    graph_stats: Optional[Dict[str, Any]] = None
) -> str:
    """
    Format analysis results as a GitHub PR comment in markdown.
    
    Args:
        pr_identifier: PR identifier (e.g., "owner/repo#123")
        mode: Analysis mode ("quick" or "deep")
        critical_count: Number of critical issues
        warning_count: Number of warnings
        info_count: Number of info-level findings
        deviations: List of deviation dictionaries
        should_fail: Whether the CI should fail
        commit_sha: Optional commit SHA analyzed
        duration_seconds: Analysis duration
        graph_stats: Optional graph statistics for deep mode
    
    Returns:
        Formatted markdown string for PR comment
    """
    total_issues = critical_count + warning_count + info_count
    
    # Status header with emoji
    if should_fail:
        status_emoji = "❌"
        status_text = "FAILED"
        status_color = "red"
    elif total_issues > 0:
        status_emoji = "⚠️"
        status_text = "PASSED WITH WARNINGS"
        status_color = "yellow"
    else:
        status_emoji = "✅"
        status_text = "PASSED"
        status_color = "green"
    
    # Build the markdown comment
    lines = []
    
    # Header
    lines.append(f"## {status_emoji} Compliance Analysis Report")
    lines.append("")
    
    # Status badge-style line
    lines.append(f"**Status**: {status_text}")
    if commit_sha:
        lines.append(f"**Commit**: `{commit_sha[:7]}`")
    lines.append(f"**Mode**: {mode.capitalize()} analysis")
    if duration_seconds > 0:
        lines.append(f"**Duration**: {duration_seconds:.1f}s")
    lines.append("")
    
    # Summary table
    lines.append("### Summary")
    lines.append("")
    lines.append("| Severity | Count |")
    lines.append("|----------|-------|")
    lines.append(f"| 🔴 Critical | {critical_count} |")
    lines.append(f"| 🟡 Warning | {warning_count} |")
    lines.append(f"| 🔵 Info | {info_count} |")
    lines.append("")
    
    # Graph stats for deep mode
    if graph_stats:
        lines.append("### Graph Statistics")
        lines.append("")
        lines.append(f"- **Entities analyzed**: {graph_stats.get('total_entities', 0):,}")
        lines.append(f"- **Relationships**: {graph_stats.get('total_relationships', 0):,}")
        lines.append(f"- **Files**: {graph_stats.get('total_files', 0)}")
        if graph_stats.get('languages'):
            langs = ", ".join(graph_stats['languages'][:5])
            lines.append(f"- **Languages**: {langs}")
        lines.append("")
    
    # Deviations grouped by severity
    if deviations:
        # Critical issues
        critical_devs = [d for d in deviations if d.get('severity', '').lower() == 'critical']
        if critical_devs:
            lines.append("<details>")
            lines.append(f"<summary><strong>🔴 Critical Issues ({len(critical_devs)})</strong></summary>")
            lines.append("")
            for dev in critical_devs:
                lines.extend(_format_deviation(dev))
            lines.append("</details>")
            lines.append("")
        
        # Warnings
        warning_devs = [d for d in deviations if d.get('severity', '').lower() == 'warning']
        if warning_devs:
            lines.append("<details>")
            lines.append(f"<summary><strong>🟡 Warnings ({len(warning_devs)})</strong></summary>")
            lines.append("")
            for dev in warning_devs:
                lines.extend(_format_deviation(dev))
            lines.append("</details>")
            lines.append("")
        
        # Info
        info_devs = [d for d in deviations if d.get('severity', '').lower() == 'info']
        if info_devs:
            lines.append("<details>")
            lines.append(f"<summary><strong>🔵 Info ({len(info_devs)})</strong></summary>")
            lines.append("")
            for dev in info_devs[:10]:  # Limit info items
                lines.extend(_format_deviation(dev))
            if len(info_devs) > 10:
                lines.append(f"*...and {len(info_devs) - 10} more info items*")
                lines.append("")
            lines.append("</details>")
            lines.append("")
    
    # Footer
    lines.append("---")
    lines.append("*Generated by [Ethereum Compliance Analyzer](https://github.com/your-org/compliance-analyzer)*")
    
    return "\n".join(lines)


def _format_deviation(deviation: Dict[str, Any]) -> List[str]:
    """Format a single deviation as markdown list items."""
    lines = []
    
    # Title with rule ID
    rule_id = deviation.get('rule_id', 'Unknown')
    description = deviation.get('description', 'No description')
    lines.append(f"#### {rule_id}")
    lines.append(f"{description}")
    lines.append("")
    
    # File location
    file_path = deviation.get('file') or deviation.get('file_path')
    line_num = deviation.get('line') or deviation.get('line_number')
    if file_path:
        if line_num:
            lines.append(f"- **Location**: `{file_path}:{line_num}`")
        else:
            lines.append(f"- **File**: `{file_path}`")
    
    # Entity name if available
    entity_name = deviation.get('entity_name')
    if entity_name:
        lines.append(f"- **Entity**: `{entity_name}`")
    
    # Recommendation
    recommendation = deviation.get('recommendation')
    if recommendation:
        lines.append(f"- **Recommendation**: {recommendation}")
    
    # Spec reference
    spec_ref = deviation.get('spec_reference')
    if spec_ref:
        lines.append(f"- **Reference**: {spec_ref}")
    
    lines.append("")
    return lines


def format_error_comment(
    pr_identifier: str,
    error_message: str,
    mode: str
) -> str:
    """
    Format an error message as a GitHub PR comment.
    
    Args:
        pr_identifier: PR identifier
        error_message: Error message to display
        mode: Analysis mode attempted
    
    Returns:
        Formatted markdown string for error comment
    """
    lines = [
        "## ⚠️ Compliance Analysis Error",
        "",
        f"Analysis of **{pr_identifier}** failed.",
        "",
        "### Error Details",
        "",
        f"```",
        error_message,
        "```",
        "",
        f"**Mode**: {mode.capitalize()}",
        "",
        "Please check the CI logs for more details or try re-running the analysis.",
        "",
        "---",
        "*Generated by [Ethereum Compliance Analyzer](https://github.com/your-org/compliance-analyzer)*"
    ]
    
    return "\n".join(lines)
